# Generated by Django 3.1.4 on 2020-12-28 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChildTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilages', models.CharField(max_length=500, null=True)),
                ('name', models.CharField(max_length=500, null=True)),
                ('extraprice', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('pnr', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fligthdate', models.DateField(null=True)),
                ('destinations', models.ManyToManyField(to='home.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('seat', models.CharField(max_length=255, null=True)),
                ('flights', models.ManyToManyField(to='home.Flight')),
                ('registereduser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.registereduser')),
                ('tickettype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.childticket')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('request', 'request'), ('suggestion', 'suggestion'), ('complaint', 'complaint')], max_length=255, null=True)),
                ('text', models.CharField(max_length=1000, null=True)),
                ('registereduser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.registereduser')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('cardNumber', models.DecimalField(decimal_places=0, max_digits=16, primary_key=True, serialize=False)),
                ('cardName', models.CharField(max_length=255, null=True)),
                ('expirationDate', models.DateField(null=True)),
                ('cvv', models.DecimalField(decimal_places=0, max_digits=3, null=True)),
                ('cardHolderName', models.CharField(max_length=255, null=True)),
                ('registereduser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.registereduser')),
            ],
        ),
    ]
