# Generated by Django 3.1.4 on 2021-01-09 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(max_length=10, null=True)),
                ('departure_time', models.DateField(null=True)),
                ('arrival_time', models.DateField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('from_airport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_airport', to='home.airport')),
                ('to_airport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_airport', to='home.airport')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip', models.CharField(choices=[('o', 'oneway'), ('r', 'roundtrip')], max_length=5)),
                ('seat', models.CharField(max_length=255, null=True)),
                ('ticket_class', models.CharField(max_length=255, null=True)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.CharField(max_length=255, null=True)),
                ('is_approval', models.CharField(max_length=1, null=True)),
                ('flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.flight')),
                ('registereduser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.registereduser')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('request', 'request'), ('suggestion', 'suggestion'), ('complaint', 'complaint')], max_length=255, null=True)),
                ('text', models.TextField()),
                ('registereduser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.registereduser')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNumber', models.DecimalField(decimal_places=0, max_digits=16, null=True)),
                ('cardName', models.CharField(max_length=255, null=True)),
                ('expirationmonth', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2, null=True)),
                ('expirationyear', models.CharField(choices=[('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29')], max_length=2, null=True)),
                ('cvv', models.DecimalField(decimal_places=0, max_digits=3, null=True)),
                ('cardHolderName', models.CharField(max_length=255, null=True)),
                ('registereduser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.registereduser')),
            ],
        ),
    ]
