# Generated by Django 3.1.4 on 2021-01-31 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('A', 'Admin'), ('U', 'User')], max_length=100, null=True)),
                ('registereduser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.registereduser')),
            ],
            options={
                'verbose_name': 'User Type',
                'verbose_name_plural': 'User Types',
                'ordering': ['user_type'],
            },
        ),
    ]
