# Generated by Django 3.1.4 on 2021-01-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_ok',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
