# Generated by Django 3.1.4 on 2021-01-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210109_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
