# Generated by Django 3.1.4 on 2021-01-06 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210105_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='airport',
        ),
        migrations.AddField(
            model_name='flight',
            name='from_airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_airport', to='home.airport'),
        ),
        migrations.AddField(
            model_name='flight',
            name='to_airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_airport', to='home.airport'),
        ),
    ]
