# Generated by Django 3.1.4 on 2021-01-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210106_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticketclass',
            new_name='ticket_class',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='extra_price',
            new_name='ticket_price',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_name',
        ),
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
