# Generated by Django 3.1.4 on 2021-02-02 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210203_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='seat',
        ),
        migrations.AddField(
            model_name='aseat',
            name='pticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ticket'),
        ),
    ]
