# Generated by Django 3.1.4 on 2021-01-09 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210109_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='registereduser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.registereduser'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='registereduser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.registereduser'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='registereduser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.registereduser'),
        ),
    ]
