# Generated by Django 3.1.3 on 2020-12-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('cardNumber', models.DecimalField(decimal_places=0, max_digits=16, primary_key=True, serialize=False)),
                ('cardName', models.CharField(max_length=255, null=True)),
                ('expirationDate', models.DateField(null=True)),
                ('cvv', models.DecimalField(decimal_places=0, max_digits=3, null=True)),
                ('cardHolderName', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='nofpassengers',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='time',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
