# Generated by Django 3.1.4 on 2021-01-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_registereduser_my_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='is_ok',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=1),
        ),
    ]
