# Generated by Django 3.1.4 on 2021-02-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='flightclass',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
