# Generated by Django 3.1.4 on 2021-01-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210106_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
