# Generated by Django 3.1.4 on 2021-01-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210106_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_approval',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
