# Generated by Django 3.1.3 on 2020-12-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201227_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
