# Generated by Django 3.1.4 on 2021-02-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_seat_flightclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='is_ok',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10, null=True),
        ),
    ]
