# Generated by Django 3.1.4 on 2021-02-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210201_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        ),
    ]
