# Generated by Django 3.1.4 on 2021-01-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210105_2337'),
        ('home', '0008_ticket_is_approval'),
    ]

    operations = [
    ]
