# Generated by Django 3.1.3 on 2020-12-27 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201227_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('request', 'request'), ('suggestion', 'suggestion'), ('complaint', 'complaint')], max_length=255, null=True)),
                ('text', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('fligthdate', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='cardName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Ticket_Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flightpnr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.flight')),
                ('Ticketid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='FirstClassTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstclass_priviliges', models.CharField(max_length=500, null=True)),
                ('Ticketid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='EconomyTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('economy_priviliges', models.CharField(max_length=500, null=True)),
                ('Ticketid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_priviliges', models.CharField(max_length=500, null=True)),
                ('Ticketid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Airport_Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flightpnr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.flight')),
                ('departure_arrival', models.ManyToManyField(to='home.Airport')),
            ],
        ),
    ]
