# Generated by Django 3.1.4 on 2021-02-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210201_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
