# Generated by Django 3.1.4 on 2021-01-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210107_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateField(null=True),
        ),
    ]
