# Generated by Django 3.1.3 on 2020-12-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201227_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilages', models.CharField(max_length=500, null=True)),
                ('name', models.CharField(max_length=500, null=True)),
                ('extraprice', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='economyticket',
            name='Ticketid',
        ),
        migrations.RemoveField(
            model_name='firstclassticket',
            name='Ticketid',
        ),
        migrations.DeleteModel(
            name='BusinessTicket',
        ),
        migrations.DeleteModel(
            name='EconomyTicket',
        ),
        migrations.DeleteModel(
            name='FirstClassTicket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='tag',
            field=models.ManyToManyField(to='home.ChildTicket'),
        ),
    ]
