# Generated by Django 3.1.3 on 2020-12-27 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20201227_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='tag',
        ),
        migrations.AddField(
            model_name='ticket',
            name='tag',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.childticket'),
            preserve_default=False,
        ),
    ]
