# Generated by Django 3.1.3 on 2020-12-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20201227_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='tag',
        ),
        migrations.AddField(
            model_name='ticket',
            name='tag',
            field=models.ManyToManyField(to='home.ChildTicket'),
        ),
    ]
